### ISSUE TITLE
phase 2 no found compression rtx3070 only cpu compression,

### ISSUE THREAD

**Issue by neo57500** [smartbitcoin/arc_plot#15]
****************************************************************************************
**                                 Phase 1: creating plot                             **
****************************************************************************************
[P1] Table 1 took 7.37045 sec
[P1] Table 2 took 37.6636 sec, found 4294856155 matches
[P1] Table 3 took 74.6866 sec, found 4292862573 matches
[P1] Table 4 took 81.4121 sec, found 4290260892 matches
[P1] Table 5 took 69.1885 sec, found 4285610435 matches
[P1] Table 6 took 62.8257 sec, found 4276127880 matches
[P1] Table 7 took 52.7722 sec, found 4257379716 matches
Phase 1 took 385.95 sec

****************************************************************************************
**                                 Phase 2: compressing plot                          **
****************************************************************************************
[prescan] took 100.203 sec
G24 MODE: 0 
[P2] Table 2.a took 22.8797 sec, wrote 0 right entries
[P2] Table 2.b took 34.9874 sec, wrote 3427281128 left entries, 3427281128 final

**Comment by smartbitcoin** [comment]
Could you upload the whole log file with the command line of your run?  the head of log file will show the configuration of your plotting setup.

**Comment by neo57500** [comment]
./arc_plot -G -r 48 -n 1 -u 256 -v 256 -t   /media/neo57/7ae84f4e-e777-4c9d-a53f-bf8f6a16a84d/  -d /media/neo57/chia3/ -p xxxxxx  -f  xxxxxxx

**Comment by neo57500** [comment]
my setup dual xeon 2697v2 256go ddr3 ecc 1800 mhz rtx 3070 2x nvme 1 tb

**Comment by neo57500** [comment]
Final Directory: /media/neo57/chia/
Stage Directory: /home/edouard/Others/Ramdisk/
Number of Plots: 6
GPU plotting 1 out of 6 (2023/01/14 16:19:08)
Found cpu ram size: 264071368
Found gpu: 1
Found gpu:0 ram size: 7925858304
GPU plotting in G24 mode: 0
using gpu 0:[ NVIDIA GeForce RTX 3070 ] for plotting.
Process ID: 4269
Number of Threads: 48
Number of Buckets P1:    2^8 (256)
Number of Buckets P3+P4: 2^8 (256)
Pool Public Key:   

Farmer Public Key: 

Working Directory:   /home/edouard/Others/Ramdisk/
Working Directory 2: /home/edouard/Others/Ramdisk/
Plot Name: 
plot-k32-2023-01-14-16-19-0c2a8d3fcfbf52d32480e5cb91152faccafc9929d2c628f37865dc97c4a5c0aa

**Comment by smartbitcoin** [comment]
so the issue is GPU plotter stop at phase 2 , table 2 ?  if plotter failed, there suppose have some errors in log.
could you retry rerun with parameter ``` --gthreads 1``` and run ``` sudo dmesg``` or ``` cat /var/log/syslog``` to check if any error in your system log.  you can also use tools like ```nvtop``` to monitor your gpu when plotting to check when gpu stop working.

is your temp drive "-t /media/neo57/7ae84f4e-e777-4c9d-a53f-bf8f6a16a84d/" a raid or just one simple plain ssd?

you can take a look at ticket : https://github.com/smartbitcoin/arc_plot/issues/12   maybe similar situation.

**Comment by neo57500** [comment]
raid 0 nvme

**Comment by neo57500** [comment]
e="/snap/snap-store/638/usr/bin/snap-store" sig=0 arch=c000003e syscall=314 compat=0 ip=0x7f893861973d code=0x50000
[   32.903587] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000300] Failed to grab modeset ownership
[   32.903741] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000300] Failed to grab modeset ownership
[   32.903824] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000300] Failed to grab modeset ownership
[   32.903893] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000300] Failed to grab modeset ownership
[   32.934673] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000300] Failed to grab modeset ownership
[   32.934813] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000300] Failed to grab modeset ownership
[   32.934898] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000300] Failed to grab modeset ownership
[   32.934984] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000300] Failed to grab modeset ownership
[   32.985471] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000300] Failed to grab modeset ownership
[   32.985617] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000300] Failed to grab modeset ownership
[   32.985706] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000300] Failed to grab modeset ownership
[   32.985786] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000300] Failed to grab modeset ownership

**Comment by smartbitcoin** [comment]
please check this post and re-install your nvidia linux driver to lastest version.

https://forums.developer.nvidia.com/t/nvdia-failed-to-grab-modeset-ownership-ubuntu-20-04/214496
