### ISSUE TITLE
[Unintended Behavior] phase 1 locked to --buckets 256 regardless of switch

### ISSUE THREAD

**Issue by Motophan** [smartbitcoin/arc_plot#17]
Related to https://github.com/smartbitcoin/arc_plot/issues/18

gentoo@arch5950x arc_plot]$ ./arc_plot -t /mnt/nvme01/ -r 16 -f [redacted] -c [redacted] -G --buckets 64 --buckets3 64
****************************************************************************************
**     ARC_PLOT   CPU + GPU plotter  version: 0.7-d38e551***************
****************************************************************************************
 
Final Directory: /mnt/nvme01/
Number of Plots: 1
GPU plotting 1 out of 1 (2023/01/14 08:23:08)
Found cpu ram size: 131816880
Found gpu: 1
Found gpu:0 ram size: 16319971328
GPU plotting in G24 mode: 0
using gpu 0:[ NVIDIA GeForce RTX 4080 ] for plotting.
Process ID: 2722
Number of Threads: 16
Number of Buckets P1:    2^8 (256)
Number of Buckets P3+P4: 2^6 (64)
Pool Puzzle Hash:  
ligma
Farmer Public Key: 
ligma
Working Directory:   /mnt/nvme01/
Working Directory 2: /mnt/nvme01/
Plot Name: 
plot-k32-2023-01-14-08-23-3e12f34ce21d9275b8675207de1b2950fee4a883810b56fc7d2d47c3907052a2

**Comment by smartbitcoin** [comment]
same ticket as https://github.com/smartbitcoin/arc_plot/issues/18 .
