### ISSUE TITLE
OOM Ubuntu 22.10 128GB RAM GPU plot

### ISSUE THREAD

**Issue by trs-80** [smartbitcoin/arc_plot#2]
OOM Ubuntu 22.10 128GB RAM GPU plot

Final Directory: /mnt/plot_drive1/chia_durable_storage/
Stage Directory: /mnt/owc/chia_temp/
Number of Plots: 1
GPU plotting 1 out of 1 (2022/12/10 15:15:17)
Found cpu ram size: 131778416
Found gpu: 1
Found gpu ram size: 10239803392
using gpu 0:[ NVIDIA GeForce RTX 3080 ] for plotting.
Process ID: 2313
Number of Threads: 14
Number of Buckets P1:    2^8 (256)
Number of Buckets P3+P4: 2^8 (256)

...

****************************************************************************************
**                                 Phase 1: creating plot                             **
****************************************************************************************
[P1] Table 1 took 8.17414 sec
[P1] Table 2 took 19.7942 sec, found 4294869370 matches
[P1] Table 3 took 39.4913 sec, found 4293104602 matches
[P1] Table 4 took 47.2025 sec, found 4290632552 matches
[P1] Table 5 took 46.664 sec, found 4286321392 matches
[P1] Table 6 took 36.4027 sec, found 4277706152 matches
[P1] Table 7 took 44.6465 sec, found 4260456684 matches
Phase 1 took 242.997 sec

****************************************************************************************
**                                 Phase 2: compressing plot                          **
****************************************************************************************
[prescan] took 144.414 sec
[P2] Table 2.a took 14.5778 sec, wrote 3427166114 right entries
Killed
...

[ 1057.904493] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-3.scope,task=arc_plot,pid=2313,uid=1000
[ 1057.904552] Out of memory: Killed process 2313 (arc_plot) total-vm:176460228kB, anon-rss:129685844kB, file-rss:74092kB, shmem-rss:128kB, UID:1000 pgtables:260128kB oom_score_adj:0
[ 1061.998300] oom_reaper: reaped process 2313 (arc_plot), now anon-rss:0kB, file-rss:79116kB, shmem-rss:8kB

Linux boots in multi-user mode so no graphical environment competing for memory or GPU.

free -g
               total        used        free      shared  buff/cache   available
Mem:             125           0         124           0           0         124
Swap:              1           0           1

**Comment by Motophan** [comment]
Do you have 32GB of swap? I found it does not crash for me even with xfce running.

**Comment by smartbitcoin** [comment]
v0.6.1 need 32G swap and in v0.6.2 already have better implementation.  128G should not have OOM issue when have no swap file.
