### ISSUE TITLE
[Feature Request] Statically link the dependent libraries in the binary

### ISSUE THREAD

**Issue by Motophan** [smartbitcoin/arc_plot#4]
Re: https://github.com/smartbitcoin/arc_plot/issues/1

This was closed as I assume the developer believed this was a support request, it is not. It was a feature request. If the libraries are statically linked in the binary I dont need to compile a ancient version of gcc and glibc and set LD_PATH.

This will dramatically reduce support requests of users who are not aware of libraries if the binary contains them and should make compatibility almost universal on linux implementations that use glibc (versus muslc in some exotic setups). There is literally no downside to do this feature, as a user who has a exotic libc setup (less than 0.078% of linux based installs) can compile and set LD_PATH as needed. 

Please reconsider
Regards

**Comment by Jacek-ghub** [comment]
You have my support.  I am on Rocky Linux (new CentOS), and don't think that I can be convinced to switch to Ubuntu.

**Comment by smartbitcoin** [comment]
in v0.6.2,  libstdc++ and libgcc already in static link,  please try it.
