### ISSUE TITLE
MMX project support

### ISSUE THREAD

**Issue by Jacek-ghub** [smartbitcoin/arc_plot#5]
Please, consider adding MMX support.  

You can take a look at paspy's or zcomputerwiz bladebit changes.  Not that many lines need to be added.  https://github.com/paspy/bladebit/tags or https://github.com/zcomputerwiz/bladebit/releases/tag/v2.0.0

It may be that more plotting is being done right now for MMX than for Chia.

**Comment by smartbitcoin** [comment]
when I have a fully implemented arc_plot, I'll try MMX.

**Comment by cdgraff** [comment]
+1

**Comment by cdgraff** [comment]
HI, @smartbitcoin some timeline to add MMX? I need to Plot a lot of TB and will love to test your plotter and share feedback and hardware used here. But I'll only plot MMX no plan to increase my Chia farm... will be awesome if can add MMX support to more people using your GPU plotter and giving feedback to you. thanks!

**Comment by smartbitcoin** [comment]
closed as mmx already published their gpu plotter.
