### ISSUE TITLE
bug gpu  rtx 3070 

### ISSUE THREAD

**Issue by neo57500** [smartbitcoin/arc_plot#6]
[P1] Table 1 took 8.06722 sec
[P1] Table 2 took 50.6836 sec, found 4294756922 matches
[P1] Table 3 took 105.576 sec, found 4292832879 matches
[P1] Table 4 took 118.854 sec, found 4290054302 matches
[P1] Table 5 took 107.66 sec, found 4285118923 matches
terminate called after throwing an instance of 'std::runtime_error'
  what():  thread failed with: fwrite() failed with: Bad address
Abandon (core dumped)

**Comment by smartbitcoin** [comment]
As mentioned in release notes,   if ssd speed is bad or after lots write without trim ,  file write will fail.
clean up your SSD and do "sudo fstrim /your_ssd_driver" will solve this issue.
If you using GPU plotter,  the speed requirement for SSD even higher.  QLC ssd need two as raid0, or use good speed MLC ssd.
